modLoader = "javafml"
loaderVersion = "*"
license = "${mod_license}"
issueTrackerURL = "${mod_issues}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_page}"
logoFile = "${mod_id}.png"
authors = "haasapenas"
description = '''${mod_description}'''
[[dependencies.trashcan]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.trashcan]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.trashcan]]
modId = "jei"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"